services:
  - type: web
    name: smartwallet
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: NODE_ENV
        value: production
